// Code generated by mockery v2.0.0. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	tododomain "github.com/thetrollfarmercodes/todoctl/todo/internal/core/todo"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

func NewRepository(t mock.TestingT) *Repository {
	m := &Repository{}
	m.Mock.Test(t)
	return m
}

// CreateTodos provides a mock function with given fields: ctx, items
func (_m *Repository) CreateTodos(ctx context.Context, items []tododomain.Todo) ([]tododomain.Todo, error) {
	ret := _m.Called(ctx, items)

	var r0 []tododomain.Todo
	if rf, ok := ret.Get(0).(func(context.Context, []tododomain.Todo) []tododomain.Todo); ok {
		r0 = rf(ctx, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tododomain.Todo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []tododomain.Todo) error); ok {
		r1 = rf(ctx, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTodos provides a mock function with given fields: ctx, page, limit, cursor
func (_m *Repository) ListTodos(ctx context.Context, page int, limit int, cursor string) ([]tododomain.Todo, string, error) {
	ret := _m.Called(ctx, page, limit, cursor)

	var r0 []tododomain.Todo
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []tododomain.Todo); ok {
		r0 = rf(ctx, page, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tododomain.Todo)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) string); ok {
		r1 = rf(ctx, page, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, page, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateTodos provides a mock function with given fields: ctx, updates
func (_m *Repository) UpdateTodos(ctx context.Context, updates []tododomain.TodoUpdate) ([]tododomain.Todo, error) {
	ret := _m.Called(ctx, updates)

	var r0 []tododomain.Todo
	if rf, ok := ret.Get(0).(func(context.Context, []tododomain.TodoUpdate) []tododomain.Todo); ok {
		r0 = rf(ctx, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tododomain.Todo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []tododomain.TodoUpdate) error); ok {
		r1 = rf(ctx, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ tododomain.Repository = (*Repository)(nil)
