// Code generated by mockery v2.0.0. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/thetrollfarmercodes/todoctl/todo/internal/core/idempotency"
)

// IdempotencyStore is an autogenerated mock type for the Store type
type IdempotencyStore struct {
	mock.Mock
}

func NewIdempotencyStore(t mock.TestingT) *IdempotencyStore {
	m := &IdempotencyStore{}
	m.Mock.Test(t)
	return m
}

// Get provides a mock function with given fields: ctx, key, scope
func (_m *IdempotencyStore) Get(ctx context.Context, key string, scope string) (*idempotency.Record, error) {
	ret := _m.Called(ctx, key, scope)

	var r0 *idempotency.Record
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *idempotency.Record); ok {
		r0 = rf(ctx, key, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idempotency.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, key, scope, status, response
func (_m *IdempotencyStore) Save(ctx context.Context, key string, scope string, status int, response []byte) error {
	ret := _m.Called(ctx, key, scope, status, response)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, []byte) error); ok {
		r0 = rf(ctx, key, scope, status, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ idempotency.Store = (*IdempotencyStore)(nil)
